Feature/custom headers per call
ExtraHorizon/javascript-sdk pull request #307
Opened 2021-07-16 08:43 UTC by jensdev

2021-08-02 09:56 UTC, ThomasReyskens commented
make options optional again in implementation

2021-08-11 12:54 UTC, ThomasReyskens commented on src/services/files/types.ts
> +  findFirst(options?: OptionsWithRql): Promise<FileDetails>;
why is the find first jsdoc gone?

2021-08-11 12:57 UTC, ThomasReyskens requested changes
open comments

2021-08-11 13:03 UTC, ThomasReyskens commented on src/services/dispatchers/dispatchers.ts
> +   * Permission | Scope | Effect
add newline before permissions, to create a table in jsdoc

2021-08-11 13:04 UTC, ThomasReyskens commented on src/services/auth/types.ts
> +   * @permission VIEW_APPLICATIONS | scope:global |
newline before permission, to be consistent

2021-08-11 14:45 UTC, jensdev commented on src/services/files/types.ts
> +  findFirst(options?: OptionsWithRql): Promise<FileDetails>;
I've added it

2021-08-11 15:07 UTC, ThomasReyskens approved these changes

2021-08-11 15:08 UTC, merged